### ISSUE TITLE
download rate very slow

### ISSUE THREAD

**Issue by blueballon** [michel-kraemer/gradle-download-task#141]
When I use this plugin to download raw assets from our nexus repo, I get a max download rate of only about 2MB/sec. 

To ensure that this is not a problem with our environment, I tired to compare the download speed to a simple groovy download function (from https://stackoverflow.com/q/14474973): 

```
def downloadFunction(String remoteUrl, String localUrl)
{
    def file = new FileOutputStream(localUrl)
    def out = new BufferedOutputStream(file)
    out << new URL(remoteUrl).openStream()
    out.close()
}
```

When I use this groovy code within the same gradle script to download the same asset, I get a factor 10 higher download rate of about 20MB/sec.

=> it seems there is an issue anywhere inside the download-task code that makes it somewhat really slow. And interestingly, the CPU load increases to 100% of one core during the whole duration of download-task - this also does not happen with the groovy download function.

**Comment by michel-kraemer** [comment]
This is very strange. I've never heard of such an issue. I can't think of anything in the code that could cause this.

The fact that you get 100% CPU usage suggests there is something else going on. Do you have an anti-virus software installed that could interfere with the plugin? Can you try running it again with the `-q` parameter to disable output so we can rule out the progress bar?

**Comment by blueballon** [comment]
The environments I used are Windows 10 and Centos7 in a Hyper-V-VM on the same Win10 machine. There is no virus scanner running on the Centos VM, but of course I cannot exclude that the virus scanner on the Win10 also affects the Centos VM. But I wonder that the simple straightforward implemetation behaves differently with much better download speed and lower cpu usage.
I tested also with and without active progress bar - but unfortunately this does neither affect the download speed nor the cpu load. 
The cpu load is caused by the java executeable itself (on windows and on linux).
I also ran a build scan, but without any additional insights.

**Comment by blueballon** [comment]
As I did not get gradle-profile working behind our proxy, I monitored the running gradle process with JVisualVM - and I got an interesting result:
The most cpu-time-consuming function with 65% self time seems to be de.undercouch.gradle.tasks.download.org.apache.commons.logging.impl.Jdk14Logger.log() - see attached screenshot from the profiling on windows (the linux result was quite similar)

![gradledownloader_cpusamples_jvisualvm](https://user-images.githubusercontent.com/1812606/64680404-02d51e80-d47e-11e9-95d8-886ff1e3b5a1.PNG)

Is there any logging functionality used by the downloader?
The progress bar was turned off during the test.

**Comment by michel-kraemer** [comment]
Thanks for the insights. Very interesting. I'm not using any logger in gradle-download-task. The plugin writes directly to the console. But internally, Apache HttpClient is used to perform the actual download, and I guess they are using a logger. But I'm not sure yet how to completely disable it so it does not consume any CPU. Maybe with a custom log configuration file or with system properties? Some hints can be found here:
https://hc.apache.org/httpcomponents-client-4.5.x/logging.html

**Comment by ALLIESXO** [comment]
For me the download task is also very slow. It starts with a maximum of 1MB/s and slows down. 
Like blueballon mentioned correctly using a simple download function inside the **same project** works with no problems. 
Also for me the "de.undercouch.gradle.tasks.download.org.apache.commons.logging.impl.Jdk14Logger.log()" causes 98% of execution time.

When downloading longer than few minutes, the download speed reaches its minimum. 
It makes it almost impossible to download bigger files.

**Comment by tylerhartwig** [comment]
I'm also experiencing slow download speeds on macOS.

**Comment by VladRassokhin** [comment]
As @blueballon and @ALLIESXO mentioned above problem is that httpclient tries to log something once each 10k is downloaded. Each 'log' creates temporary exception and fills stacktrace, that's quite expensive operation.
I've managed to workaround it locally by adding
`org.gradle.jvmargs=-Dde.undercouch.gradle.tasks.download.org.apache.commons.logging.Log=de.undercouch.gradle.tasks.download.org.apache.commons.logging.impl.NoOpLog` into `$HOME/.gradle/gradle.properties`

**Comment by michel-kraemer** [comment]
Thanks for the insights, @VladRassokhin! I really appreciate this. I just pushed a patch and will release a new version 4.0.1 now.

**Comment by cdancy** [comment]
@michel-kraemer @VladRassokhin I'm still seeing this issue with latest plugin on gradle `6.0.1`. Using `wget` I can download a 2GB file in about 3 minutes on our network. The same file when downloaded with this plugin takes about half an hour. I tried using the system property above but still nothing. My impl looks like:
```
download {
    src "something"
    dest localBuildDir
    overwrite false
    quiet true
}
```
Is there anything I can do to debug this on your guys end? I do see when I enable `--debug` on gradle the http wire log is logging all of the data received. Not sure if that's expected or not...

**Comment by michel-kraemer** [comment]
@cdancy Which version of gradle-download-task do you use?

**Comment by cdancy** [comment]
@michel-kraemer latest and greatest version on a stand-alone project.

**Comment by michel-kraemer** [comment]
@cdancy As I said, if you still encounter the problem with the latest version, please open a new issue. Also provide a small reproducer. Thanks.
